default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: db
  username: postgres
  password: root

development:
  <<: *default

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
