source 'https://rubygems.org'
git_source(:github) { |repo| 'https://github.com/#{repo}.git' }

ruby '3.0.0'

gem 'rails', '~> 7.0.6'

gem 'sqlite3', '~> 1.4'

gem 'pg', '~> 1.5'

gem 'puma', '~> 5.0'

gem 'redis', '~> 4.0'

gem 'bcrypt', '~> 3.1.7'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[ mingw mswin x64_mingw jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', require: false

gem 'rack-cors'

gem 'httparty', '~> 0.17.3'

group :development, :test do
  gem 'debug', platforms: %i[ mri mingw x64_mingw ]

  gem 'rspec-rails', '~> 6.0.0'

  gem 'rubocop-rails', require: false

  gem 'rubocop-rspec', require: false

  gem 'pry', '~> 0.13.1'
end

group :production do
  gem 'rails_same_site_cookie'
end
